/*
 * Xmlform.io REST API
 * Xmlform.io REST API for working with web forms backed by XML data
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@xmlform.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.xmlform;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for JwtLogin200Response
 */
class JwtLogin200ResponseTest {
    private final JwtLogin200Response model = new JwtLogin200Response();

    /**
     * Model tests for JwtLogin200Response
     */
    @Test
    void testJwtLogin200Response() {
        // TODO: test JwtLogin200Response
    }

    /**
     * Test the property 'token'
     */
    @Test
    void tokenTest() {
        // TODO: test token
    }

}
