/*
 * Xmlform.io REST API
 * Xmlform.io REST API for working with web forms backed by XML data
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@xmlform.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.xmlform;

import io.ApiException;
import io.xmlform.JwtLogin200Response;
import io.xmlform.JwtLoginRequest;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for XmlformioApi
 */
@Disabled
public class XmlformioApiTest {

    private final XmlformioApi api = new XmlformioApi();

    /**
     * Converts provided xmlform.io form data into XML document
     *
     * Converts provided xmlform.io form data into XML document
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void formToXmlTest() throws ApiException {
        Object body = null;
        String response = api.formToXml(body);

        // TODO: test validations
    }
    /**
     * JWT Token endpoint
     *
     * Authenticates and returns a JWT token
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void jwtLoginTest() throws ApiException {
        JwtLoginRequest jwtLoginRequest = null;
        JwtLogin200Response response = api.jwtLogin(jwtLoginRequest);

        // TODO: test validations
    }
    /**
     * Converts provided XML document into xmlform.io form data
     *
     * Converts XML document into form data, ready for editing in an xmlform.io web form. #Example code Example code for various languages can be found at [Xml to Form examples](https://xmlform.io/docs/xml-to-form) 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void xmlToFormTest() throws ApiException {
        String body = null;
        String response = api.xmlToForm(body);

        // TODO: test validations
    }
}
